# .github/workflows/update_readme.yml
name: Update README with Minecraft Version

  workflow_dispatch:  

jobs:
  update_readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - uses: actions/checkout@v3

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      - name: Read Versions from config.yml
        id: vars
        run: |
          OLD_VERSION=$(yq -r '.["old-version"]' config.yml)
          NEW_VERSION=$(yq -r '.["new-version"]' config.yml)
          echo "old_version=$OLD_VERSION" >> $GITHUB_OUTPUT
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Replace version in README
        run: |
          OLD_VERSION="${{ steps.vars.outputs.old_version }}"
          NEW_VERSION="${{ steps.vars.outputs.new_version }}"
          sed -i "s/${OLD_VERSION}/${NEW_VERSION}/g" README.md

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update README with Minecraft version ${{ steps.vars.outputs.new_version }}'

