# .github/workflows/update_readme.yml
name: Update README with Minecraft Version

on:
  push:
    branches:
      - main

  workflow_dispatch:  

jobs:
  update_readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - uses: actions/checkout@v3

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      - name: Get Minecraft Version from config.yml
        id: vars
        run: |
          MC_VERSION=$(yq -r '.["mc-version"]' config.yml)
          echo "mc_version=$MC_VERSION" >> $GITHUB_OUTPUT

      - name: Replace Version in README
        run: |
          MC_VERSION="${{ steps.vars.outputs.mc_version }}"
          sed -i "s/1.21.5/${MC_VERSION}/g" README.md

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update README with Minecraft version variable'

